### ISSUE TITLE
Navigation error when sidemenu is opened

### ISSUE THREAD

**Issue by IgorGZd** [EhsnJmli/curtain#1]
I like this Widget but I found this error. When side menu is opened nothing happens when try to navigate in onPageChange event with Navigator.push, example: 
`Navigator.push(context, MaterialPageRoute(builder: (context) => LogoutPage()));`
I fixed this in file side_bar.dart replacing order of lines 126 and 127:

```
if (isTablet) { Navigator.pop(context); }
widget.changeIndex(index);
```

I wish you would fix that in the next version. Thank you.

**Comment by EhsnJmli** [comment]
Thanks for your contribution. I appreciate it. 
I just fixed it in version 0.1.3+1
